[project]
name = "ticketrouting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "joblib>=1.6.0",
    "numpy>=2.5.3",
    "psycopg2-binary>=2.9.13",
    "pydantic>=2.13.5",
    "scikit-learn>=1.9.1",
    "sqlalchemy>=2.0.54",
    "supabase>=2.31.0",
    "uvicorn[standard]>=0.53.0",
]
